// ============================================
// MOCK DATA — Devices for Go2Hand
// Used until real Supabase data is wired up
// ============================================

import { Device } from "@/types/device";

export const FEATURED_DEVICES: Device[] = [
    {
        id: "iphone-14-pro-max-256-purple",
        brand: "Apple",
        model: "iPhone 14 Pro Max",
        fullName: "iPhone 14 Pro Max - Deep Purple",
        storage: "256 GB",
        color: "Deep Purple",
        grade: "A",
        conditionLabel: "Excellent",
        price: 689,
        originalPrice: 1099,
        images: [
            "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-14-pro-finish-select-202209-6-7inch-deeppurple?wid=800&hei=800&fmt=png-alpha",
            "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-14-pro-finish-select-202209-6-7inch-deeppurple?wid=800&hei=800&fmt=png-alpha",
            "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-14-pro-finish-select-202209-6-7inch-deeppurple?wid=800&hei=800&fmt=png-alpha",
        ],
        isVerified: true,
        inspectedDate: "Jan 12, 2025",
        batteryHealth: 91,
        conditionChecks: [
            { label: "Screen — No scratches", status: "ok" },
            { label: "Battery — 91% health", status: "ok" },
            { label: "Camera — All lenses clear", status: "ok" },
            { label: "Charging port — Working", status: "ok" },
            { label: "Face ID — Functional", status: "ok" },
            { label: "Back glass — Minor scuff", status: "warn" },
            { label: "Speakers — Clear audio", status: "ok" },
            { label: "Buttons — All responsive", status: "ok" },
        ],
        specs: [
            { label: "Brand", value: "Apple" },
            { label: "Model", value: "iPhone 14 Pro Max" },
            { label: "Storage", value: "256 GB", highlighted: true },
            { label: "RAM", value: "6 GB" },
            { label: "Colour", value: "Deep Purple" },
            {
                label: "Display",
                value: "6.7″ Super Retina XDR OLED · ProMotion 120Hz",
            },
            { label: "Processor", value: "Apple A16 Bionic" },
            {
                label: "Camera",
                value: "48MP Main · 12MP Ultra-Wide · 12MP 3× Telephoto",
            },
            {
                label: "Battery",
                value: "4,323 mAh · MagSafe · Lightning → USB-C adapter",
            },
            { label: "OS", value: "iOS 17.4 (upgradeable)" },
            { label: "Network", value: "5G · Wi-Fi 6 · Bluetooth 5.3" },
            { label: "SIM", value: "Dual SIM (Nano + eSIM)" },
            {
                label: "IMEI Status",
                value: "Clean — Not Blacklisted",
                highlighted: true,
            },
            { label: "iCloud", value: "Unlocked", highlighted: true },
        ],
        seller: {
            id: "seller-minh-hoang",
            name: "Minh Hoang",
            initials: "MH",
            avatarColor: "from-teal-600 to-emerald-500",
            isVerified: true,
            memberSince: "Mar 2022",
            location: "Ho Chi Minh City",
            rating: 4.96,
            totalSales: 142,
            responseTime: "< 1hr",
        },
        reviews: [
            {
                id: "r1",
                reviewerName: "Trung Nguyen",
                reviewerInitials: "TN",
                avatarColor: "bg-violet-500",
                rating: 5,
                date: "2 weeks ago",
                text: "Exactly as described. Packaging was careful, device arrived quickly. The screen is pristine and battery health is genuinely 91%. Escrow made me feel safe — would buy again.",
            },
            {
                id: "r2",
                reviewerName: "Linh Pham",
                reviewerInitials: "LP",
                avatarColor: "bg-amber-500",
                rating: 4,
                date: "1 month ago",
                text: 'Great phone, condition matches the "A grade" rating. Minor scuff on back as noted. Seller was responsive and shipped same day. Highly recommend.',
            },
        ],
        totalReviews: 38,
        averageRating: 4.9,
        shippingProvider: "J&T Express",
        shippingDays: "2–4 days",
        imeiStatus: "clean",
        iCloudStatus: "unlocked",
        carrierStatus: "unlocked",
        availableStorage: ["128 GB", "256 GB", "512 GB", "1 TB"],
        storagePrices: {
            "128 GB": 599,
            "256 GB": 689,
            "512 GB": 799,
            "1 TB": 949,
        },
        category: "Smartphones",
    },
    {
        id: "iphone-14-pro-128-gold",
        brand: "Apple",
        model: "iPhone 14 Pro",
        fullName: "iPhone 14 Pro - Gold",
        storage: "128 GB",
        color: "Gold",
        grade: "A",
        conditionLabel: "Excellent",
        price: 589,
        originalPrice: 999,
        images: [
            "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-14-pro-finish-select-202209-6-1inch-gold?wid=800&hei=800&fmt=png-alpha",
        ],
        isVerified: true,
        inspectedDate: "Jan 8, 2025",
        batteryHealth: 88,
        conditionChecks: [],
        specs: [],
        seller: {
            id: "seller-minh-hoang",
            name: "Minh Hoang",
            initials: "MH",
            avatarColor: "from-teal-600 to-emerald-500",
            isVerified: true,
            memberSince: "Mar 2022",
            location: "Ho Chi Minh City",
            rating: 4.96,
            totalSales: 142,
            responseTime: "< 1hr",
        },
        reviews: [],
        totalReviews: 24,
        averageRating: 4.8,
        shippingProvider: "J&T Express",
        shippingDays: "2–4 days",
        imeiStatus: "clean",
        iCloudStatus: "unlocked",
        carrierStatus: "unlocked",
        availableStorage: ["128 GB", "256 GB"],
        storagePrices: { "128 GB": 589, "256 GB": 679 },
        category: "Smartphones",
    },
    {
        id: "iphone-13-pro-max-256-blue",
        brand: "Apple",
        model: "iPhone 13 Pro Max",
        fullName: "iPhone 13 Pro Max - Sierra Blue",
        storage: "256 GB",
        color: "Sierra Blue",
        grade: "B",
        conditionLabel: "Good",
        price: 479,
        originalPrice: 899,
        images: [
            "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-13-pro-max-finish-select-2021-q4-sierra-blue?wid=800&hei=800&fmt=png-alpha",
        ],
        isVerified: true,
        inspectedDate: "Dec 20, 2024",
        batteryHealth: 84,
        conditionChecks: [],
        specs: [],
        seller: {
            id: "seller-an-tran",
            name: "An Tran",
            initials: "AT",
            avatarColor: "from-blue-500 to-indigo-500",
            isVerified: true,
            memberSince: "Aug 2023",
            location: "Hanoi",
            rating: 4.7,
            totalSales: 38,
            responseTime: "< 3hrs",
        },
        reviews: [],
        totalReviews: 12,
        averageRating: 4.7,
        shippingProvider: "Giao Hàng Nhanh",
        shippingDays: "3–5 days",
        imeiStatus: "clean",
        iCloudStatus: "unlocked",
        carrierStatus: "unlocked",
        availableStorage: ["128 GB", "256 GB", "512 GB"],
        storagePrices: { "128 GB": 419, "256 GB": 479, "512 GB": 569 },
        category: "Smartphones",
    },
    {
        id: "galaxy-s23-ultra-256-black",
        brand: "Samsung",
        model: "Galaxy S23 Ultra",
        fullName: "Galaxy S23 Ultra - Phantom Black",
        storage: "256 GB",
        color: "Phantom Black",
        grade: "A",
        conditionLabel: "Excellent",
        price: 649,
        originalPrice: 1199,
        images: [
            "https://images.samsung.com/is/image/samsung/p6pim/levant/sm-s918bztheub/gallery/levant-galaxy-s23-ultra-s918-sm-s918bztheub-535846695?$650_519_PNG$",
        ],
        isVerified: true,
        inspectedDate: "Jan 5, 2025",
        batteryHealth: 94,
        conditionChecks: [],
        specs: [],
        seller: {
            id: "seller-bao-le",
            name: "Bao Le",
            initials: "BL",
            avatarColor: "from-orange-500 to-red-500",
            isVerified: false,
            memberSince: "Jun 2023",
            location: "Da Nang",
            rating: 4.5,
            totalSales: 21,
            responseTime: "< 6hrs",
        },
        reviews: [],
        totalReviews: 9,
        averageRating: 4.5,
        shippingProvider: "J&T Express",
        shippingDays: "2–4 days",
        imeiStatus: "clean",
        iCloudStatus: "unlocked",
        carrierStatus: "unlocked",
        availableStorage: ["256 GB", "512 GB"],
        storagePrices: { "256 GB": 649, "512 GB": 749 },
        category: "Smartphones",
    },
    {
        id: "iphone-15-pro-max-256-titanium",
        brand: "Apple",
        model: "iPhone 15 Pro Max",
        fullName: "iPhone 15 Pro Max - Natural Titanium",
        storage: "256 GB",
        color: "Natural Titanium",
        grade: "A+",
        conditionLabel: "Excellent",
        price: 899,
        originalPrice: 1299,
        images: [
            "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-15-pro-finish-select-202309-6-7inch-naturaltitanium?wid=800&hei=800&fmt=png-alpha",
        ],
        isVerified: true,
        inspectedDate: "Jan 15, 2025",
        batteryHealth: 98,
        conditionChecks: [],
        specs: [],
        seller: {
            id: "seller-minh-hoang",
            name: "Minh Hoang",
            initials: "MH",
            avatarColor: "from-teal-600 to-emerald-500",
            isVerified: true,
            memberSince: "Mar 2022",
            location: "Ho Chi Minh City",
            rating: 4.96,
            totalSales: 142,
            responseTime: "< 1hr",
        },
        reviews: [],
        totalReviews: 5,
        averageRating: 4.9,
        shippingProvider: "J&T Express",
        shippingDays: "2–4 days",
        imeiStatus: "clean",
        iCloudStatus: "unlocked",
        carrierStatus: "unlocked",
        availableStorage: ["256 GB", "512 GB", "1 TB"],
        storagePrices: { "256 GB": 899, "512 GB": 999, "1 TB": 1149 },
        category: "Smartphones",
    },
];

// Helper: get device by ID
export function getDeviceById(id: string): Device | undefined {
    return FEATURED_DEVICES.find((d) => d.id === id);
}

// Helper: get similar devices (same category, excluding current)
export function getSimilarDevices(currentId: string, limit = 4): Device[] {
    return FEATURED_DEVICES.filter((d) => d.id !== currentId).slice(0, limit);
}
